# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [56]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [57]:

city_df = pd.read_csv('city_data.csv')
city_df.head()

,Unnamed: 0,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Bredasdorp,-34.53,20.04,69.80,52,0,9.17,ZA,1603287646
1,1,Paamiut,61.99,-49.67,34.63,84,100,18.61,GL,1603287853
2,2,Tasiilaq,65.61,-37.64,30.20,86,75,3.36,GL,1603287667
3,3,Jamestown,42.10,-79.24,61.32,93,90,9.17,US,1603287393
4,4,Saskylakh,71.92,114.08,12.29,95,90,4.38,RU,1603287634

In [58]:
del city_df['Unnamed: 0']
city_df.head()

,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Bredasdorp,-34.53,20.04,69.80,52,0,9.17,ZA,1603287646
1,Paamiut,61.99,-49.67,34.63,84,100,18.61,GL,1603287853
2,Tasiilaq,65.61,-37.64,30.20,86,75,3.36,GL,1603287667
3,Jamestown,42.10,-79.24,61.32,93,90,9.17,US,1603287393
4,Saskylakh,71.92,114.08,12.29,95,90,4.38,RU,1603287634

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [59]:
gmaps.configure(g_key)
locations = city_df[["Latitude", "Longitude"]]
humidity = city_df["Humidity"]

In [60]:
fig=gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations,humidity,max_intensity=30,point_radius=5)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.
#Values used are Temperature between 70 -80 degrees, wind speed <15 and cloudiness 0

In [76]:
index_cities = city_df.loc[(city_df['Temperature']<85) & (city_df['Temperature']>70) & (city_df['Wind Speed']<10) & (city_df['Cloudiness']<10)]
index_cities

,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
57,Castro,-24.79,-50.01,74.66,61,3,7.47,BR,1603287866
107,Cabatuan,10.88,122.49,77.11,89,5,6.73,PH,1603287877
134,Coahuayana Viejo,18.73,-103.68,73.40,83,5,2.59,MX,1603287884
251,Cabo San Lucas,22.89,-109.91,71.60,56,5,5.82,MX,1603287923
296,Frontera,26.93,-101.45,73.99,67,7,3.00,MX,1603287942
359,Lantawan,10.62,123.98,75.85,87,1,6.08,PH,1603287963
428,Nacala,-14.54,40.67,84.85,56,1,7.92,MZ,1603287984
432,Kahului,20.89,-156.47,70.65,68,1,3.87,US,1603287985
438,São Filipe,14.90,-24.50,84.67,62,0,2.62,CV,1603287987
456,Houma,29.60,-90.72,72.63,100,1,8.05,US,1603287740
484,Nānākuli,21.39,-158.15,73.38,88,1,3.36,US,1603288002
488,San Patricio,28.02,-97.52,76.51,94,1,4.70,US,1603287910
518,Makakilo City,21.35,-158.09,73.92,88,1,3.36,US,1603288012

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [77]:
#create hotel_df dataframe 
hotel_df = pd.DataFrame(index_cities)
hotel_df.insert(1, 'Hotel Name', "")
hotel_df.head()

,City Name,Hotel Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
57,Castro,,-24.79,-50.01,74.66,61,3,7.47,BR,1603287866
107,Cabatuan,,10.88,122.49,77.11,89,5,6.73,PH,1603287877
134,Coahuayana Viejo,,18.73,-103.68,73.40,83,5,2.59,MX,1603287884
251,Cabo San Lucas,,22.89,-109.91,71.60,56,5,5.82,MX,1603287923
296,Frontera,,26.93,-101.45,73.99,67,7,3.00,MX,1603287942

In [94]:

#parameters
params = {
    "radius": 5000,
    "type": "lodging",
    "keyword": "Hotel",
    "key": g_key
}

#Loop through rows to get latitude and longitude 
for index, row in hotel_df.iterrows():
    lat = row['Latitude']
    lng = row['Longitude']
    
     # add location to params and query
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
    response = requests.get(base_url, params=params).json()

    try:
        hotel_df.loc[index, 'Hotel Name'] = response["results"][0]["name"]
        print(f"The nearest hotel is {response['results'][0]['name']}")
    except:
        print("No hotel found")

The nearest hotel is Buganville Palace Hotel
No hotel found
The nearest hotel is Hotel Posada Navideña
The nearest hotel is Waldorf Astoria Los Cabos Pedregal
The nearest hotel is Fiesta Inn Monclova
The nearest hotel is Marick Beach Resort
The nearest hotel is Nacala Plaza Business Design Hotel
The nearest hotel is Maui Beach Hotel
The nearest hotel is Hotel Ocean View & Restaurante Seafood
The nearest hotel is Candlewood Suites Houma
The nearest hotel is Polynesia Lodging & Conference
The nearest hotel is Americas Best Value Inn Sinton
The nearest hotel is Hampton Inn & Suites Oahu/Kapolei

In [97]:
hotel_df

,City Name,Hotel Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
57,Castro,Buganville Palace Hotel,-24.79,-50.01,74.66,61,3,7.47,BR,1603287866
107,Cabatuan,,10.88,122.49,77.11,89,5,6.73,PH,1603287877
134,Coahuayana Viejo,Hotel Posada Navideña,18.73,-103.68,73.40,83,5,2.59,MX,1603287884
251,Cabo San Lucas,Waldorf Astoria Los Cabos Pedregal,22.89,-109.91,71.60,56,5,5.82,MX,1603287923
296,Frontera,Fiesta Inn Monclova,26.93,-101.45,73.99,67,7,3.00,MX,1603287942
359,Lantawan,Marick Beach Resort,10.62,123.98,75.85,87,1,6.08,PH,1603287963
428,Nacala,Nacala Plaza Business Design Hotel,-14.54,40.67,84.85,56,1,7.92,MZ,1603287984
432,Kahului,Maui Beach Hotel,20.89,-156.47,70.65,68,1,3.87,US,1603287985
438,São Filipe,Hotel Ocean View & Restaurante Seafood,14.90,-24.50,84.67,62,0,2.62,CV,1603287987
456,Houma,Candlewood Suites Houma,29.60,-90.72,72.63,100,1,8.05,US,1603287740
484,Nānākuli,Polynesia Lodging & Conference,21.39,-158.15,73.38,88,1,3.36,US,1603288002
488,San Patricio,Americas Best Value Inn Sinton,28.02,-97.52,76.51,94,1,4.70,US,1603287910
518,Makakilo City,Hampton Inn & Suites Oahu/Kapolei,21.35,-158.09,73.92,88,1,3.36,US,1603288012

In [99]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City Name}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [100]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))